[[rule]]
toolName = "run_shell_command"
decision = "allow"
priority = 100
commandPrefix = [ "uv" ]

[[rule]]
toolName = "run_shell_command"
decision = "allow"
priority = 100
commandPrefix = [ "uvx" ]

[[rule]]
toolName = "run_shell_command"
decision = "allow"
priority = 100
commandPrefix = [ "gh" ]

[[rule]]
toolName = "run_shell_command"
decision = "allow"
priority = 100
commandPrefix = [ "base64" ]

[[rule]]
toolName = "run_shell_command"
decision = "allow"
priority = 100
commandPrefix = [ "echo" ]

[[rule]]
toolName = "run_shell_command"
decision = "allow"
priority = 100
commandPrefix = [ "xargs" ]

[[rule]]
toolName = "run_shell_command"
decision = "allow"
priority = 100
commandPrefix = [ "gemini" ]