[[rule]]
toolName = "run_shell_command"
decision = "allow"
priority = 100
commandPrefix = [ "printf" ]

[[rule]]
toolName = "run_shell_command"
decision = "allow"
priority = 100
commandPrefix = [ "docker", "timeout" ]

[[rule]]
toolName = "run_shell_command"
decision = "allow"
priority = 100
commandPrefix = [ "docker", "sleep", "kill", "cat" ]
